### PR TITLE
Add torture tests

### PR DESCRIPTION
**Pull request by josharian**
@mdempsky @dr2chase @bradfitz thoughts on this? Is this a good home for these? I was thinking we could also add fixed torture tests here as well. And maybe only run fixed ones when -short is present? All ideas and opinions welcome.

### CODE REVIEW

**Comment by dr2chase** [comment]
We definitely need this; we were discussing it last week over lunch.
Not 100% sure on the "good home" issue; I'm not doubtful, I just don't know enough about that.
I think we had maybe 4 "bad" compilations?  There's gogo/protobuf(15537), etldlen (16407), mewmew-lexer (14934), Dave Cheney's generated test (14774).  Even those these have been improved, they're still not great.  One heuristic to look into is a comparison of tall-vs-wide flow graphs -- I think etldlen is wide, not tall, and that means that the "old" non-sparse method works quite well (this is a hypothetical heuristic, not yet tested).

**Comment by josharian** [comment]
Who was the "we" that discussed this? Want to pull the others into this thread?

**Comment by dr2chase** [comment]
"We" was the usual Cambridge Go suspects -- me, Austin, Rick, @cherrymui, @quentinmit, maybe Than (CAM-Googler, transferred to Go -- Russ is still on pretend-I-was-hit-by-a-bus paternal leave).  I assume @randall77 will care, and probably also Robert G.

I pinged a representative sample.

**Comment by josharian** [comment]
Another to add: issue 16361

**Comment by josharian** [comment]
Another torture test: issue 17926

**Comment by josharian** [comment]
More:

https://github.com/golang/go/issues/8225
https://github.com/golang/go/issues/18602

Guess I'll just keep collecting these here until I figure out what to do with them. :)

**Comment by josharian** [comment]
Another: https://github.com/golang/go/issues/19751

**Comment by rsc** [comment]
Sure, go ahead.

**Comment by josharian** [comment]
Not migrated to x/tools/compilebench, because I'm worried it'll bloat the repo--these files are large. There are also possibly license questions about the code. It can just sit in my local tree until I decide what to do with it.

**Pull request closed without merging**
