### PR TITLE
compilebench: clean up _hello_ after run

### PR DESCRIPTION
**Pull request by josharian**
@rsc or @bradfitz can I get a LGTM on this? If so, I'll push directly rather than merge to make history nice.

Yay awkward github code reviews. If you have suggestions for a better way, great. Otherwise, I'll keep doing this.

### CODE REVIEW

**Comment by bradfitz** [comment]
LGTM.

My @LetsUseGerrit bot needs to run as a daemon, but it's very close.

**Comment by josharian** [comment]
Thanks. Pushed to master. Not sure what @LetsUseGerrit is, but I'd love to use gerrit. :)

**Comment by rsc** [comment]
As far as I'm concerned, you can just push whatever you like here. :-)

**Comment by josharian** [comment]
Ok. That'll keep things simple. :) And if you see something you don't like, holler and I'll clean it up.

**Pull request closed without merging**
